; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "GogolCrosshairs"
#define MyAppVersion "1.4.0"
#define MyAppPublisher "LoloLeDev"
#define MyAppURL "https://www.gogolcrosshairs.netlify.app"
#define MyAppExeName "GogolCrosshairs.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{85859DBB-F960-4FB9-8913-BFD91A542C4E}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=commandline
OutputBaseFilename=GogolCrosshais-Setup
SetupIconFile=C:\Users\Loévan\Desktop\code\LoloCrossHair\logo.ico
SolidCompression=yes
WizardStyle=modern dark

[Languages]
Name: "french"; MessagesFile: "compiler:Languages\French.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\Loévan\Desktop\code\LoloCrossHair\release\win-unpacked\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Loévan\Desktop\code\LoloCrossHair\release\win-unpacked\locales\*"; DestDir: "{app}\locales"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\Loévan\Desktop\code\LoloCrossHair\release\win-unpacked\resources\*"; DestDir: "{app}\resources"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\Loévan\Desktop\code\LoloCrossHair\release\win-unpacked\chrome_100_percent.pak"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Loévan\Desktop\code\LoloCrossHair\release\win-unpacked\chrome_200_percent.pak"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Loévan\Desktop\code\LoloCrossHair\release\win-unpacked\d3dcompiler_47.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Loévan\Desktop\code\LoloCrossHair\release\win-unpacked\ffmpeg.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Loévan\Desktop\code\LoloCrossHair\release\win-unpacked\icudtl.dat"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Loévan\Desktop\code\LoloCrossHair\release\win-unpacked\libEGL.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Loévan\Desktop\code\LoloCrossHair\release\win-unpacked\libGLESv2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Loévan\Desktop\code\LoloCrossHair\release\win-unpacked\LICENSE.electron.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Loévan\Desktop\code\LoloCrossHair\release\win-unpacked\LICENSES.chromium.html"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Loévan\Desktop\code\LoloCrossHair\release\win-unpacked\resources.pak"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Loévan\Desktop\code\LoloCrossHair\release\win-unpacked\snapshot_blob.bin"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Loévan\Desktop\code\LoloCrossHair\release\win-unpacked\v8_context_snapshot.bin"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Loévan\Desktop\code\LoloCrossHair\release\win-unpacked\vk_swiftshader.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Loévan\Desktop\code\LoloCrossHair\release\win-unpacked\vk_swiftshader_icd.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Loévan\Desktop\code\LoloCrossHair\release\win-unpacked\vulkan-1.dll"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

